name: test-ssh

on:
  workflow_dispatch:

jobs:
  ssh:
    name: ssh
    runs-on: ubuntu-26.04
    steps:
      - name: ssh
        uses: sa3lej/action-tmtv@v1
        with:
          timeout-minutes: 300
