name: test-cont

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.3
          modules: 'qtwebsockets'
