name: test-cont

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-26.04
    steps:
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.12.*'
          modules: 'qtwebsockets'

  test2:
    runs-on: xcode-27
    steps:
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.12.*'
          modules: 'qtwebsockets'
