name: test-cont

on:
  workflow_dispatch:

jobs:
  test1:
    name: "test1 on ${{ matrix.dist.name }}"
    strategy:
      fail-fast: false
      matrix:
        dist:
          - name: debiantrixie
            image: 'debian:trixie'
          - name: debianforky
            image: 'debian:forky'
          - name: fedora44
            image: 'fedora:44'
          - name: fedora45
            image: 'fedora:45'
          - name: fedorarawhide
            image: 'fedora:rawhide'
          - name: alpine324
            image: 'alpine:3.24'
          - name: alpineedge
            image: 'alpine:edge'
          - name: ubunturesolute
            image: 'ubuntu:resolute'
          - name: ubuntustonking
            image: 'ubuntu:stonking'
          - name: rocky10
            image: 'rockylinux/rockylinux:10'

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.dist.image }}
    steps:
      - name: 1
        run: |
          echo "Hello from $(uname -a)"
          cat /etc/os-release
